/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cloud/v1/orgs/{orgId}/agents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/sessions/{sessionId}/pull-requests": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["listSessionPullRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/sessions/{sessionId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["getSessionReviewState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/sessions/{sessionId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/sessions/{sessionId}/chat-events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["replayClientEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/sessions/{sessionId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["streamClientEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/sessions/{sessionId}/terminal-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createTerminalTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/terminal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upgrade to a terminal WebSocket using a short-lived ticket. */
        get: operations["connectTerminal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/sessions/{sessionId}/workspace/files": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["listWorkspaceFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/sessions/{sessionId}/workspace/file": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["readWorkspaceFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/sessions/{sessionId}/workspace/diff": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["getWorkspaceDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/provider-connections": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get: operations["listProviderConnections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AgentCapability: "interface.chat" | "interface.tui" | "model.catalog" | "model.custom" | "attachments" | "browser.preview" | "review.execute" | "session.resume";
        /** @enum {string} */
        AgentInstallationState: "installed" | "not_installed" | "unknown" | "not_applicable";
        /** @enum {string} */
        AgentAuthenticationState: "authorized" | "unauthorized" | "unknown" | "not_applicable";
        /** @enum {string} */
        AgentOrganizationPolicy: "not_applicable" | "allowed" | "denied";
        AgentAvailability: {
            /** @description Effective host readiness after installation, authentication, and organization policy. */
            available: boolean;
            installation: components["schemas"]["AgentInstallationState"];
            authentication: components["schemas"]["AgentAuthenticationState"];
            organizationPolicy: components["schemas"]["AgentOrganizationPolicy"];
            /** @description Host-supplied explanation when the agent is unavailable. */
            reason?: string;
        };
        AgentProfile: {
            id: string;
            label: string;
            capabilities: components["schemas"]["AgentCapability"][];
            availability: components["schemas"]["AgentAvailability"];
        };
        ErrorEnvelope: {
            error: string;
            code: string;
            message: string;
            requestId: string;
            details?: {
                [key: string]: unknown;
            };
        };
        PageInfo: {
            hasMore: boolean;
            nextCursor?: string;
        };
        Project: {
            id: string;
            orgId: string;
            displayName: string;
            /** Format: uri */
            repositoryUrl: string;
            defaultBranch: string;
            config: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateProjectInput: {
            displayName: string;
            /** Format: uri */
            repositoryUrl: string;
            defaultBranch: string;
            config?: {
                [key: string]: unknown;
            };
        };
        ProjectPage: {
            items: components["schemas"]["Project"][];
            page: components["schemas"]["PageInfo"];
        };
        /** @enum {string} */
        SessionKind: "worker" | "orchestrator";
        /** @enum {string} */
        SessionActivityState: "active" | "idle" | "waiting_input" | "blocked" | "exited";
        /** @enum {string} */
        SessionStatus: "working" | "needs_input" | "pr_open" | "draft" | "review_pending" | "ci_failed" | "changes_requested" | "approved" | "mergeable" | "merged" | "exited" | "idle" | "terminated" | "no_signal";
        Turn: {
            id: string;
            sessionId: string;
            /** Format: int64 */
            userMessageSequence: number;
            /** @enum {string} */
            state: "queued" | "provisioning" | "running" | "cancel_requested" | "completed" | "failed";
            attemptCount: number;
            errorMessage?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Session: {
            id: string;
            orgId: string;
            projectId: string;
            kind: components["schemas"]["SessionKind"];
            harness: string;
            displayName: string;
            branch: string;
            activityState: components["schemas"]["SessionActivityState"];
            status: components["schemas"]["SessionStatus"];
            capabilities?: components["schemas"]["AgentCapability"][];
            runtimeConnected: boolean;
            runtimeState?: string;
            runtimeError?: string;
            activeTurn?: components["schemas"]["Turn"];
            isTerminated: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateSessionInput: {
            projectId: string;
            kind: components["schemas"]["SessionKind"];
            harness: string;
            displayName: string;
            prompt: string;
            providerConnectionId?: string;
        };
        SessionPage: {
            items: components["schemas"]["Session"][];
            page: components["schemas"]["PageInfo"];
        };
        /** @enum {string} */
        PullRequestState: "draft" | "open" | "merged" | "closed";
        /** @enum {string} */
        CIState: "unknown" | "pending" | "passing" | "failing";
        /** @enum {string} */
        PullRequestCheckStatus: "unknown" | "queued" | "in_progress" | "passed" | "failed" | "skipped" | "cancelled";
        /** @enum {string} */
        ReviewDecision: "none" | "approved" | "changes_requested" | "review_required";
        /** @enum {string} */
        MergeabilityState: "unknown" | "mergeable" | "conflicting" | "blocked" | "unstable";
        PullRequestFailingCheck: {
            name: string;
            status: components["schemas"]["PullRequestCheckStatus"];
            conclusion: string;
            url?: string;
        };
        PullRequestCISummary: {
            state: components["schemas"]["CIState"];
            failingChecks: components["schemas"]["PullRequestFailingCheck"][];
        };
        PullRequestReviewCommentLink: {
            url?: string;
            file?: string;
            line?: number;
            autoInjectReview: boolean;
        };
        PullRequestUnresolvedReviewer: {
            reviewerId: string;
            count: number;
            links: components["schemas"]["PullRequestReviewCommentLink"][];
            reviewUrl?: string;
            isBot?: boolean;
        };
        PullRequestSubmittedReview: {
            reviewerId: string;
            verdict: components["schemas"]["ReviewDecision"];
            body?: string;
            reviewUrl?: string;
            /** Format: date-time */
            submittedAt: string;
            isBot?: boolean;
            autoInjectReview: boolean;
        };
        PullRequestReviewSummary: {
            decision: components["schemas"]["ReviewDecision"];
            hasUnresolvedHumanComments: boolean;
            unresolvedBy: components["schemas"]["PullRequestUnresolvedReviewer"][];
            reviews: components["schemas"]["PullRequestSubmittedReview"][];
        };
        PullRequestConflictFile: {
            path: string;
            url?: string;
        };
        PullRequestMergeabilitySummary: {
            state: components["schemas"]["MergeabilityState"];
            reasons: string[];
            pullRequestUrl: string;
            conflictFiles: components["schemas"]["PullRequestConflictFile"][];
        };
        PullRequestSummary: {
            url: string;
            htmlUrl?: string;
            number: number;
            title: string;
            state: components["schemas"]["PullRequestState"];
            provider: string;
            repository: string;
            author: string;
            sourceBranch: string;
            targetBranch: string;
            headSha: string;
            additions: number;
            deletions: number;
            changedFiles: number;
            ci: components["schemas"]["PullRequestCISummary"];
            review: components["schemas"]["PullRequestReviewSummary"];
            mergeability: components["schemas"]["PullRequestMergeabilitySummary"];
            /** Format: date-time */
            stateChangedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            observedAt: string;
            /** Format: date-time */
            ciObservedAt: string;
            /** Format: date-time */
            reviewObservedAt: string;
        };
        SessionPullRequests: {
            sessionId: string;
            pullRequests: components["schemas"]["PullRequestSummary"][];
        };
        /** @enum {string} */
        AOReviewRunStatus: "running" | "complete" | "delivered" | "failed" | "cancelled";
        /** @enum {string} */
        AOReviewVerdict: "" | "approved" | "changes_requested";
        /** @enum {string} */
        AOReviewState: "needs_review" | "running" | "up_to_date" | "changes_requested" | "ineligible";
        AOReviewRun: {
            id: string;
            reviewId: string;
            sessionId: string;
            batchId: string;
            harness: string;
            pullRequestUrl: string;
            targetSha: string;
            status: components["schemas"]["AOReviewRunStatus"];
            verdict: components["schemas"]["AOReviewVerdict"];
            body: string;
            providerReviewId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            deliveredAt?: string;
            autoInjectReview: boolean;
        };
        AOPullRequestReviewState: {
            pullRequestUrl: string;
            pullRequestNumber: number;
            title: string;
            targetSha: string;
            status: components["schemas"]["AOReviewState"];
            /** @description Head SHA of the newest completed run that does not match targetSha. */
            staleTargetSha?: string;
            latestRun?: components["schemas"]["AOReviewRun"];
            previousRun?: components["schemas"]["AOReviewRun"];
        };
        SessionReviewState: {
            sessionId: string;
            reviewerHandleId?: string;
            reviewerHarness?: string;
            reviews: components["schemas"]["AOPullRequestReviewState"][];
            runs: components["schemas"]["AOReviewRun"][];
        };
        UserMessageEvent: {
            sessionId: string;
            /** Format: int64 */
            sequence: number;
            /** @constant */
            type: "chat.user_message";
            payload: {
                text: string;
            };
            /** Format: date-time */
            createdAt: string;
        };
        AssistantDeltaEvent: {
            sessionId: string;
            /** Format: int64 */
            sequence: number;
            /** @constant */
            type: "chat.assistant_delta";
            payload: {
                text: string;
            };
            /** Format: date-time */
            createdAt: string;
        };
        TurnStartedEvent: {
            sessionId: string;
            /** Format: int64 */
            sequence: number;
            /** @constant */
            type: "chat.turn_started";
            payload: {
                /** Format: int64 */
                requestSequence?: number;
            };
            /** Format: date-time */
            createdAt: string;
        };
        TurnCompletedEvent: {
            sessionId: string;
            /** Format: int64 */
            sequence: number;
            /** @constant */
            type: "chat.turn_completed";
            payload: {
                /** Format: int64 */
                requestSequence?: number;
                isError?: boolean;
                error?: string;
            };
            /** Format: date-time */
            createdAt: string;
        };
        TurnInterruptedEvent: {
            sessionId: string;
            /** Format: int64 */
            sequence: number;
            /** @constant */
            type: "chat.turn_interrupted";
            payload: {
                /** Format: int64 */
                requestSequence: number;
            };
            /** Format: date-time */
            createdAt: string;
        };
        TurnAbortedEvent: {
            sessionId: string;
            /** Format: int64 */
            sequence: number;
            /** @constant */
            type: "chat.turn_aborted";
            payload: {
                /** Format: int64 */
                requestSequence?: number;
                error?: string;
            };
            /** Format: date-time */
            createdAt: string;
        };
        InterruptRequestedEvent: {
            sessionId: string;
            /** Format: int64 */
            sequence: number;
            /** @constant */
            type: "chat.interrupt_requested";
            payload: {
                source?: string;
            };
            /** Format: date-time */
            createdAt: string;
        };
        ClientEvent: components["schemas"]["UserMessageEvent"] | components["schemas"]["AssistantDeltaEvent"] | components["schemas"]["TurnStartedEvent"] | components["schemas"]["TurnCompletedEvent"] | components["schemas"]["TurnInterruptedEvent"] | components["schemas"]["TurnAbortedEvent"] | components["schemas"]["InterruptRequestedEvent"];
        ClientEventPage: {
            events: components["schemas"]["ClientEvent"][];
            hasMore: boolean;
            /**
             * Format: int64
             * @description Highest sequence returned, or the supplied after cursor when the page is empty.
             */
            nextAfter: number;
        };
        /** @enum {string} */
        TerminalKind: "agent" | "workspace";
        /** @enum {string} */
        TerminalScope: "terminal:read" | "terminal:operate" | "terminal:dangerous-input-block";
        TerminalTicket: {
            ticket: string;
            /** @description Lifetime in seconds. */
            expiresIn: number;
            scopes: components["schemas"]["TerminalScope"][];
        };
        WorkspaceEntry: {
            name: string;
            path: string;
            isDir: boolean;
            /** Format: int64 */
            size: number;
            mode: string;
            /** Format: date-time */
            modTime: string;
        };
        WorkspaceEntryPage: {
            path: string;
            items: components["schemas"]["WorkspaceEntry"][];
            page: components["schemas"]["PageInfo"];
        };
        WorkspaceFile: {
            path: string;
            content: string;
            /** Format: int64 */
            size: number;
        };
        /** @enum {string} */
        WorkspaceFileStatus: "unmodified" | "modified" | "added" | "deleted" | "renamed" | "untracked" | "copied" | "changed";
        WorkspaceDiffFile: {
            path: string;
            oldPath?: string;
            status: components["schemas"]["WorkspaceFileStatus"];
            staged?: string;
            unstaged?: string;
            additions: number;
            deletions: number;
            binary: boolean;
        };
        WorkspaceDiff: {
            status: string;
            unstaged: string;
            staged: string;
            combined: string;
            diffBaseRef: string;
            diffBaseSha?: string;
            files: components["schemas"]["WorkspaceDiffFile"][];
            untrackedFiles: string[];
            truncated: {
                combined: boolean;
                stats: boolean;
            };
        };
        /** @enum {string} */
        ProviderName: "daytona" | "claude-code" | "codex" | "cursor";
        ProviderPublicConfig: {
            /** Format: uri */
            apiUrl?: string;
            /** @enum {string} */
            target?: "us" | "eu";
            /** @enum {string} */
            credentialType?: "oauth_token" | "api_key" | "access_token";
        };
        RedactedProviderConnection: {
            id: string;
            provider: components["schemas"]["ProviderName"];
            label: string;
            config: components["schemas"]["ProviderPublicConfig"];
            /** @enum {string} */
            validationState: "pending" | "valid" | "invalid";
            /** Format: date-time */
            validatedAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
    };
    responses: {
        /** @description Standard Cloud API error. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        OrgId: string;
        SessionId: string;
        Cursor: string;
        Limit: number;
        EventLimit: number;
        /** @description Return events with a sequence strictly greater than this value. */
        After: number;
        /** @description Reusing a key with the same command returns the original result.
         *     Reusing it with a different command returns an IDEMPOTENCY_CONFLICT.
         *      */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent profiles supplied by the runtime and organization host. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        agents: components["schemas"]["AgentProfile"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of projects in the tenant. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header: {
                /** @description Reusing a key with the same command returns the original result.
                 *     Reusing it with a different command returns an IDEMPOTENCY_CONFLICT.
                 *      */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectInput"];
            };
        };
        responses: {
            /** @description Project created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        project: components["schemas"]["Project"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listSessions: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                projectId?: string;
            };
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of sessions in the tenant. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header: {
                /** @description Reusing a key with the same command returns the original result.
                 *     Reusing it with a different command returns an IDEMPOTENCY_CONFLICT.
                 *      */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionInput"];
            };
        };
        responses: {
            /** @description Session created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        session: components["schemas"]["Session"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        session: components["schemas"]["Session"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listSessionPullRequests: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Normalized provider pull-request observations for the session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPullRequests"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSessionReviewState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AO review planning state and recorded runs for the session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionReviewState"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header: {
                /** @description Reusing a key with the same command returns the original result.
                 *     Reusing it with a different command returns an IDEMPOTENCY_CONFLICT.
                 *      */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text: string;
                };
            };
        };
        responses: {
            /** @description Message accepted and durably appended. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        event: components["schemas"]["UserMessageEvent"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    replayClientEvents: {
        parameters: {
            query?: {
                /** @description Return events with a sequence strictly greater than this value. */
                after?: components["parameters"]["After"];
                limit?: components["parameters"]["EventLimit"];
            };
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client-visible events after the supplied sequence. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientEventPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    streamClientEvents: {
        parameters: {
            query?: {
                /** @description Return events with a sequence strictly greater than this value. */
                after?: components["parameters"]["After"];
            };
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Replay followed by live client-visible events. Each SSE data field
             *     contains a ClientEvent; the SSE id is its sequence.
             *      */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createTerminalTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    kind: components["schemas"]["TerminalKind"];
                };
            };
        };
        responses: {
            /** @description Short-lived, single-use terminal access ticket. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerminalTicket"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    connectTerminal: {
        parameters: {
            query: {
                ticket: string;
                after?: number;
                kind?: components["schemas"]["TerminalKind"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebSocket protocol upgrade accepted. */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listWorkspaceFiles: {
        parameters: {
            query?: {
                path?: string;
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of entries in a workspace directory. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceEntryPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    readWorkspaceFile: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description UTF-8 workspace file contents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceFile"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getWorkspaceDiff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace changes relative to the session compare base. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceDiff"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProviderConnections: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redacted provider connection metadata. Secrets are never returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        providerConnections: components["schemas"]["RedactedProviderConnection"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
